
DELIMITER //
CREATE TRIGGER check_rating
BEFORE INSERT ON user
FOR EACH ROW
  BEGIN
    IF NEW.rating < 10 && NEW.rating > 0 THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'WRONG rating VALUE';
    END IF;
  END //
DELIMITER ;