-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 13:48:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gadget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gadget` (
  `idgadget` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `price` INT NULL,
  `gadgetcol` VARCHAR(45) NULL,
  `Company_idCompany` INT NOT NULL,
  PRIMARY KEY (`idgadget`, `Company_idCompany`),
  INDEX `fk_gadget_Company_idx` (`Company_idCompany` ASC),
  CONSTRAINT `fk_gadget_Company`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `gadget` VARCHAR(45) NULL,
  `age` INT NULL,
  `usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gadget_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gadget_has_user` (
  `gadget_idgadget` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`gadget_idgadget`, `user_iduser`),
  INDEX `fk_gadget_has_user_user1_idx` (`user_iduser` ASC),
  INDEX `fk_gadget_has_user_gadget1_idx` (`gadget_idgadget` ASC),
  CONSTRAINT `fk_gadget_has_user_gadget1`
    FOREIGN KEY (`gadget_idgadget`)
    REFERENCES `mydb`.`gadget` (`idgadget`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gadget_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


